services:
  bot:
    build: 
      context: ./bot
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./uploads:/app/uploads:ro
      - ./output:/app/output:rw
    depends_on:
      browser:
        condition: service_healthy
    networks:
      - linkedin_easy_apply_bot

  browser:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2g
    networks:
      linkedin_easy_apply_bot:
        aliases:
          - browser
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4444 || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    
  video_recorder:
    image: selenium/video:ffmpeg-4.3.1-20230123
    volumes:
      - ./video:/videos
    depends_on:
      - browser
    environment:
      - DISPLAY_CONTAINER_NAME=browser
      - FILE_NAME=video_$LI_EAB_NOW.mp4
    networks:
      - linkedin_easy_apply_bot

networks:
  linkedin_easy_apply_bot: